package com.ibm.crail.spark.tools.schema

/**
  * Created by atr on 23.11.16.
  */
object TPCDS {

  //  Table("time_dim",
  //    partitionColumns = Nil,
  //    't_time_sk                 .int,
  //    't_time_id                 .string,
  //    't_time                    .int,
  //    't_hour                    .int,
  //    't_minute                  .int,
  //    't_second                  .int,
  //    't_am_pm                   .string,
  //    't_shift                   .string,
  //    't_sub_shift               .string,
  //    't_meal_time               .string),
  case class time_dim(t_time_sk: Int,
                      t_time_id: String,
                      t_time: Int,
                      t_hour: Int,
                      t_minute: Int,
                      t_second: Int,
                      t_am_pm: String,
                      t_shift: String,
                      t_sub_shift: String,
                      t_meal_time: String)


  //  Table("store",
  //    partitionColumns = Nil,
  //    's_store_sk                .int,
  //    's_store_id                .string,
  //    's_rec_start_date          .string,
  //    's_rec_end_date            .string,
  //    's_closed_date_sk          .int,
  //    's_store_name              .string,
  //    's_number_employees        .int,
  //    's_floor_space             .int,
  //    's_hours                   .string,
  //    's_manager                 .string,
  //    's_market_id               .int,
  //    's_geography_class         .string,
  //    's_market_desc             .string,
  //    's_market_manager          .string,
  //    's_division_id             .int,
  //    's_division_name           .string,
  //    's_company_id              .int,
  //    's_company_name            .string,
  //    's_street_number           .string,
  //    's_street_name             .string,
  //    's_street_type             .string,
  //    's_suite_number            .string,
  //    's_city                    .string,
  //    's_county                  .string,
  //    's_state                   .string,
  //    's_zip                     .string,
  //    's_country                 .string,
  //    's_gmt_offset              .decimal(5,2),
  //    's_tax_precentage          .decimal(5,2))

  case class store(
                    s_store_sk: Int,
                    s_store_id: String,
                    s_rec_start_date: String,
                    s_rec_end_date: String,
                    s_closed_date_sk: Int,
                    s_store_name: String,
                    s_number_employees: Int,
                    s_floor_space: Int,
                    s_hours: String,
                    s_manager: String,
                    s_market_id: Int,
                    s_geography_class: String,
                    s_market_desc: String,
                    s_market_manager: String,
                    s_division_id: Int,
                    s_division_name: String,
                    s_company_id: Int,
                    s_company_name: String,
                    s_street_number: String,
                    s_street_name: String,
                    s_street_type: String,
                    s_suite_number: String,
                    s_city: String,
                    s_county: String,
                    s_state: String,
                    s_zip: String,
                    s_country: String,
                    s_gmt_offset: Float,
                    s_tax_precentage: Float)


  //  Table("date_dim",
  //    partitionColumns = Nil,
  //    'd_date_sk                 .int,
  //    'd_date_id                 .string,
  //    'd_date                    .string,
  //    'd_month_seq               .int,
  //    'd_week_seq                .int,
  //    'd_quarter_seq             .int,
  //    'd_year                    .int,
  //    'd_dow                     .int,
  //    'd_moy                     .int,
  //    'd_dom                     .int,
  //    'd_qoy                     .int,
  //    'd_fy_year                 .int,
  //    'd_fy_quarter_seq          .int,
  //    'd_fy_week_seq             .int,
  //    'd_day_name                .string,
  //    'd_quarter_name            .string,
  //    'd_holiday                 .string,
  //    'd_weekend                 .string,
  //    'd_following_holiday       .string,
  //    'd_first_dom               .int,
  //    'd_last_dom                .int,
  //    'd_same_day_ly             .int,
  //    'd_same_day_lq             .int,
  //    'd_current_day             .string,
  //    'd_current_week            .string,
  //    'd_current_month           .string,
  //    'd_current_quarter         .string,
  //    'd_current_year            .string),

  case class date_dim(
                       d_date_sk: Int,
                       d_date_id: String,
                       d_date: String,
                       d_month_seq: Int,
                       d_week_seq: Int,
                       d_quarter_seq: Int,
                       d_year: Int,
                       d_dow: Int,
                       d_moy: Int,
                       d_dom: Int,
                       d_qoy: Int,
                       d_fy_year: Int,
                       d_fy_quarter_seq: Int,
                       d_fy_week_seq: Int,
                       d_day_name: String,
                       d_quarter_name: String,
                       d_holiday: String,
                       d_weekend: String,
                       d_following_holiday: String,
                       d_first_dom: Int,
                       d_last_dom: Int,
                       d_same_day_ly: Int,
                       d_same_day_lq: Int,
                       d_current_day: String,
                       d_current_week: String,
                       d_current_month: String,
                       d_current_quarter: String,
                       d_current_year: String)


  //  Table("store_sales",
  //    partitionColumns = "ss_sold_date_sk" :: Nil,
  //    'ss_sold_date_sk      .int,
  //    'ss_sold_time_sk      .int,
  //    'ss_item_sk           .int,
  //    'ss_customer_sk       .int,
  //    'ss_cdemo_sk          .int,
  //    'ss_hdemo_sk          .int,
  //    'ss_addr_sk           .int,
  //    'ss_store_sk          .int,
  //    'ss_promo_sk          .int,
  //    'ss_ticket_number     .int,
  //    'ss_quantity          .int,
  //    'ss_wholesale_cost    .decimal(7,2),
  //    'ss_list_price        .decimal(7,2),
  //    'ss_sales_price       .decimal(7,2),
  //    'ss_ext_discount_amt  .decimal(7,2),
  //    'ss_ext_sales_price   .decimal(7,2),
  //    'ss_ext_wholesale_cost.decimal(7,2),
  //    'ss_ext_list_price    .decimal(7,2),
  //    'ss_ext_tax           .decimal(7,2),
  //    'ss_coupon_amt        .decimal(7,2),
  //    'ss_net_paid          .decimal(7,2),
  //    'ss_net_paid_inc_tax  .decimal(7,2),
  //    'ss_net_profit        .decimal(7,2)),

  case class store_sales(
                          ss_sold_date_sk: Int,
                          ss_sold_time_sk: Int,
                          ss_item_sk: Int,
                          ss_customer_sk: Int,
                          ss_cdemo_sk: Int,
                          ss_hdemo_sk: Int,
                          ss_addr_sk: Int,
                          ss_store_sk: Int,
                          ss_promo_sk: Int,
                          ss_ticket_number: Int,
                          ss_quantity: Int,
                          ss_wholesale_cost: Float,
                          ss_list_price: Float,
                          ss_sales_price: Float,
                          ss_ext_discount_amt: Float,
                          ss_ext_sales_price: Float,
                          ss_ext_wholesale_cost: Float,
                          ss_ext_list_price: Float,
                          ss_ext_tax: Float,
                          ss_coupon_amt: Float,
                          ss_net_paid: Float,
                          ss_net_paid_inc_tax: Float,
                          ss_net_profit: Float)

  //Table("item",
  //partitionColumns = Nil,
  //'i_item_sk                 .int,
  //'i_item_id                 .string,
  //'i_rec_start_date          .string,
  //'i_rec_end_date            .string,
  //'i_item_desc               .string,
  //'i_current_price           .decimal(7,2),
  //'i_wholesale_cost          .decimal(7,2),
  //'i_brand_id                .int,
  //'i_brand                   .string,
  //'i_class_id                .int,
  //'i_class                   .string,
  //'i_category_id             .int,
  //'i_category                .string,
  //'i_manufact_id             .int,
  //'i_manufact                .string,
  //'i_size                    .string,
  //'i_formulation             .string,
  //'i_color                   .string,
  //'i_units                   .string,
  //'i_container               .string,
  //'i_manager_id              .int,
  //'i_product_name            .string),

  case class item(
    i_item_sk                 : Int,
    i_item_id                 : String,
    i_rec_start_date          : String,
    i_rec_end_date            : String,
    i_item_desc               : String,
    i_current_price           : Float,
    i_wholesale_cost          : Float,
    i_brand_id                : Int,
    i_brand                   : String,
    i_class_id                : Int,
    i_class                   : String,
    i_category_id             : Int,
    i_category                : String,
    i_manufact_id             : Int,
    i_manufact                : String,
    i_size                    : String,
    i_formulation             : String,
    i_color                   : String,
    i_units                   : String,
    i_container               : String,
    i_manager_id              : Int,
    i_product_name            : String)
}